### ISSUE TITLE
报错显示Can not find tools.jar under java home

### ISSUE THREAD

**Issue by taibaiyifeng** [LandGrey/copagent#1]
详情如图片所示
![图片](https://user-images.githubusercontent.com/12912903/91438858-9d508c80-e89e-11ea-957f-f29b29ebe028.png)

**Comment by LandGrey** [comment]
使用 jdk 目录下的 java 执行，保证安装的 jdk 相关自带库里有 tools.jar

**Comment by taibaiyifeng** [comment]
兼容性不够啊，明天再试试，谢谢老哥

**Comment by taibaiyifeng** [comment]
可以用了，效果可以，给你点赞
