### ISSUE TITLE
日志中并未生成类对应的风险高低

### ISSUE THREAD

**Issue by taibaiyifeng** [LandGrey/copagent#2]
这段代码逻辑有问题
![图片](https://user-images.githubusercontent.com/12912903/91556195-e3702380-e964-11ea-8f8a-0a87e94b6700.png)

异常类名无法导出
![图片](https://user-images.githubusercontent.com/12912903/91556507-65f8e300-e965-11ea-8e50-2f2657b73b66.png)

**Comment by taibaiyifeng** [comment]
![图片](https://user-images.githubusercontent.com/12912903/91556895-123ac980-e966-11ea-9cf0-69511ca782db.png)

**Comment by LandGrey** [comment]
那些 [ 开头的类名本来就没办法导出，没有生成对应的风险类是不是目标 jvm 里运行的不是正常的 java web 项目
