### ISSUE TITLE
jdk11无法检测

### ISSUE THREAD

**Issue by J1a-wei** [LandGrey/copagent#5]
本机jdk11

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-post-Debian-1deb10u1, mixed mode, sharing)

java -jar cop.jar
[INFO] Version    : 1.3
[INFO] Build Time : 2020-09-14 19:54:48
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 30379 /app.jar

按回车后再次出现这个信息

[INFO] Version    : 1.3
[INFO] Build Time : 2020-09-14 19:54:48
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 30379 /app.jar
  [2]: 30732 cop.jar

此时多了项目本身的进程，再次按回车(选1)后，后面就未响应了

**Comment by J1a-wei** [comment]
已经排查到问题，jdk11无需加一些启动参数（无需tools.jar这个包)。 主函数逻辑有点问题，当没有启动参数的时候重新进入到开始的select阶段，应该是死循环了。 自己仅写vm.loadAgent 这行逻辑在jdk11是可以注入进去的。

**Comment by LandGrey** [comment]
> 已经排查到问题，jdk11无需加一些启动参数（无需tools.jar这个包)。 主函数逻辑有点问题，当没有启动参数的时候重新进入到开始的select阶段，应该是死循环了。 自己仅写vm.loadAgent 这行逻辑在jdk11是可以注入进去的。

感谢提交代码，pr 已 merge
